- name: Install nginx
  become: yes
  yum: name=nginx state=latest
  notify: Restart nginx

- name: Make sure nginx server running by port {{nginx_port}}
  become: yes
  template:
    src: nginx.config
    dest: "/etc/nginx/conf.d/default.conf"
  register: nginx_change_config

- set_fact:
    nginx_config_change: "{{nginx_change_config.changed}}"

- name: Restart nginx server
  become: yes
  service:
    name: nginx
    state: restarted
    enabled: yes
  when: nginx_config_change

- name: Start nginx server
  become: yes
  service:
    name: nginx
    state: started
    enabled: yes
