- name: Install nginx
  yum: name=nginx state=latest
  become: yes

- name: Make sure nginx server running by port {{nginx_port}}
  template:
    src: nginx.config
    dest: "/etc/nginx/conf.d/default.conf"
  become: yes

- name: Start nginx server
  service:
    name: nginx
    state: restarted
    enabled: yes
  become: yes
