---
- hosts: webserver1
  vars_files:
    - config/webserverOne.yml
  tasks:
    - name: include roles
      include_role:
        name: nodejs

    - name: Install nginx
      yum:
        name: nginx
        state: latest
      become: yes

    - name: Make sure nginx server running by port 8080
      copy:
        src: ./nginx.config
        dest: "/etc/nginx/conf.d/default.conf"
      become: yes

    - name: Start nginx server
      service:
        name: nginx
        state: restarted
        enabled: yes
      become: yes 

- hosts: webserver2
  vars_files:
    - config/webserverTwo.yml
  tasks:
    - name: include roles
      include_role:
        name: nodejs